/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kontrinex_solutions;

import com.placeholder.PlaceHolder;
import java.awt.Image;
import java.io.File;
import java.sql.ResultSet;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 
 * Subject - Social and Professional Project Management
 * Code Developed By Developer 1 -Ruzaik Mohomad
 * Student Number - 1821173
 * Group - 1
 */
public class add_stock extends javax.swing.JPanel {

    /**
     * Creates new form dashboard
     */
    public add_stock() {
        initComponents();
        //camera tab ----------------
        jLabel16.setVisible(false);
        new PlaceHolder(jTextField8, "Search Item Here");
        jTextField2.setEditable(false);
        jTextField2.setText("Camera");
        itemnameload();
        cameralensesize();
        cammegapixecl();
        //------------------------------
        
        //DVR tab-----------------------
        
        jLabel27.setVisible(false);
        new PlaceHolder(jTextField12, "Search Item Here");
        jTextField7.setText("DVR");
        jTextField7.setEditable(false);
        dvritemname();
        dvrchannel();
        
    }

    static String path = "";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jTextField4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jTextField8 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSpinner1 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jSpinner3 = new javax.swing.JSpinner();
        jLabel23 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jSpinner4 = new javax.swing.JSpinner();
        jLabel29 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jTextField12 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jComboBox6 = new javax.swing.JComboBox<>();
        jLabel33 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jTextField14 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jComboBox7 = new javax.swing.JComboBox<>();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jSpinner5 = new javax.swing.JSpinner();
        jLabel40 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jSpinner6 = new javax.swing.JSpinner();
        jTextField19 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jComboBox8 = new javax.swing.JComboBox<>();
        jLabel48 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jTextField20 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 204, 204), null, null));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel1.setText("Item Name ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 101, 23));

        jLabel2.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel2.setText("Model Number");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 101, 25));

        jLabel3.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel3.setText("Type");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 81, 101, 29));

        jLabel4.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel4.setText("Lense Size");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 116, 101, 29));

        jLabel5.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel5.setText("Mega Pixcel");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 151, 101, 27));

        jLabel6.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel6.setText("Quantity");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 189, 101, 27));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/9.gif"))); // NOI18N
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 180, 30, 20));

        jLabel7.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel7.setText("Cost Price");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 227, 101, 41));

        jComboBox1.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 21, 150, 23));

        jTextField1.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 50, 184, 25));

        jTextField2.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 81, 184, 29));

        jComboBox2.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 116, 184, 29));

        jComboBox3.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        jPanel1.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 151, 184, 27));

        jTextField4.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 227, 184, 37));

        jLabel8.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel8.setText("Barcode");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 20, 107, 23));

        jTextField5.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 21, 189, 23));

        jLabel9.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel9.setText("Image");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 58, 107, -1));

        jLabel10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 50, 189, 116));

        jButton3.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/image.png"))); // NOI18N
        jButton3.setText("Upload");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 172, 189, -1));

        jLabel11.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel11.setText("Selling Price");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 211, 107, 28));

        jTextField6.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 212, 189, 28));

        jLabel13.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel13.setText("Warrenty");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 246, 107, 22));

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/shopping-bag (1).png"))); // NOI18N
        jPanel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 40, 40));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/loop.png"))); // NOI18N
        jPanel6.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 40, 40));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/delete item.png"))); // NOI18N
        jPanel6.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 30, 40));

        jButton6.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jButton6.setText("Add Item");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 149, 50));

        jButton7.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jButton7.setText("   Update Item");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 74, 149, 50));

        jButton8.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jButton8.setText("  Delete Item");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 135, 149, 46));

        jTextField8.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        jTextField8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField8KeyReleased(evt);
            }
        });
        jPanel6.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 192, 149, 34));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(637, 20, 171, 248));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "item name", "model number", "type", "lense size", "megapixcel", "quantitty", "cost price", "barcode", "image", "selling price", "warrenty"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 286, 798, 210));

        jSpinner1.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        jPanel1.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 184, 184, 32));

        jSpinner2.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        jPanel1.add(jSpinner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 246, 189, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-add-15.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 30, -1));

        jTabbedPane1.addTab("Cameras", jPanel1);

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox4.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        jPanel7.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 21, 150, 23));

        jLabel17.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel17.setText("Item Name ");
        jPanel7.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 101, 23));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-add-15.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 30, -1));

        jTextField3.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        jPanel7.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 50, 184, 25));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/9.gif"))); // NOI18N
        jPanel7.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 180, 30, 20));

        jLabel18.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel18.setText("Model Number");
        jPanel7.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 101, 25));

        jLabel19.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel19.setText("Type");
        jPanel7.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 81, 101, 29));

        jTextField7.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        jPanel7.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 81, 184, 29));

        jLabel20.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel20.setText("Channels");
        jPanel7.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 116, 101, 29));

        jComboBox5.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        jPanel7.add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 116, 184, 29));

        jLabel21.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel21.setText("Description");
        jPanel7.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 151, 101, 27));

        jLabel22.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel22.setText("Quantity");
        jPanel7.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 189, 101, 27));

        jSpinner3.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        jPanel7.add(jSpinner3, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 184, 184, 32));

        jLabel23.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel23.setText("Cost Price");
        jPanel7.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 227, 101, 41));

        jTextField9.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        jPanel7.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 227, 184, 37));

        jTextField10.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        jPanel7.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 21, 189, 23));

        jLabel24.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel24.setText("Barcode");
        jPanel7.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 20, 107, 23));

        jLabel25.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel25.setText("Image");
        jPanel7.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 58, 107, -1));

        jLabel26.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 50, 189, 116));

        jButton5.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/image.png"))); // NOI18N
        jButton5.setText("Upload");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 172, 189, -1));

        jLabel28.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel28.setText("Selling Price");
        jPanel7.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 211, 107, 28));

        jTextField11.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        jPanel7.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 212, 189, 28));

        jSpinner4.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        jPanel7.add(jSpinner4, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 246, 189, -1));

        jLabel29.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel29.setText("Warrenty");
        jPanel7.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 246, 107, 22));
        jPanel7.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 150, 180, 30));

        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/shopping-bag (1).png"))); // NOI18N
        jPanel8.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 40, 40));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/loop.png"))); // NOI18N
        jPanel8.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 40, 40));

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/delete item.png"))); // NOI18N
        jPanel8.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 30, 40));

        jButton9.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jButton9.setText("Add Item");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 149, 50));

        jButton10.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jButton10.setText("   Update Item");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 74, 149, 50));

        jButton11.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jButton11.setText("  Delete Item");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 135, 149, 46));

        jTextField12.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        jTextField12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField12KeyReleased(evt);
            }
        });
        jPanel8.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 192, 149, 34));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "item name", "model number", "type", "channels", "description", "quantitty", "cost price", "barcode", "image", "selling price", "warrenty"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 227, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("DVR", jPanel2);

        jComboBox6.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N

        jLabel33.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel33.setText("Item Name ");

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-add-15.png"))); // NOI18N
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jTextField14.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N

        jLabel35.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel35.setText("Model Number");

        jLabel36.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel36.setText("Type");

        jTextField15.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N

        jLabel37.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel37.setText("Category");

        jComboBox7.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N

        jLabel38.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel38.setText("Description");

        jLabel39.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel39.setText("Quantity");

        jSpinner5.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N

        jLabel40.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel40.setText("Cost Price");

        jTextField16.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N

        jLabel41.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel41.setText("Barcode");

        jLabel44.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel44.setText("Selling Price");

        jTextField18.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N

        jSpinner6.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N

        jLabel46.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel46.setText("Warrenty");

        jLabel47.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel47.setText("Color");

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Red", "Green", "White", "Silver", "Gold", "Blue", "Yellow" }));

        jLabel48.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel48.setText("Length");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jSpinner5, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel9Layout.createSequentialGroup()
                            .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(4, 4, 4)
                            .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(2, 2, 2)
                            .addComponent(jSpinner6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel9Layout.createSequentialGroup()
                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel9Layout.createSequentialGroup()
                                    .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(4, 4, 4)
                                    .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(22, 22, 22)
                                    .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel9Layout.createSequentialGroup()
                                    .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(4, 4, 4)
                                    .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jComboBox8, 0, 199, Short.MAX_VALUE)
                                .addComponent(jTextField17))))))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton12)
                            .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSpinner6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(4, 4, 4)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSpinner5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/shopping-bag (1).png"))); // NOI18N
        jPanel10.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 40, 40));

        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/loop.png"))); // NOI18N
        jPanel10.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 40, 40));

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/delete item.png"))); // NOI18N
        jPanel10.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 30, 40));

        jButton13.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jButton13.setText("Add Item");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 149, 50));

        jButton14.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jButton14.setText("   Update Item");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 74, 149, 50));

        jButton15.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jButton15.setText("  Delete Item");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 135, 149, 46));

        jTextField20.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        jTextField20.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField20KeyReleased(evt);
            }
        });
        jPanel10.add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 192, 149, 34));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Name", "Model", "Type", "Category", "Description", "Quantity", "Cost Price", "Barcode", "Selling Price", "Warrenty"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(222, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Accessories", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 839, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 723, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Camera Parts", jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 839, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 723, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Security Devices and Others", jPanel5);

        add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        JFileChooser f = new JFileChooser();
        f.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter fil = new FileNameExtensionFilter("*.IMAGE", "jpeg");
        f.addChoosableFileFilter(fil);
        int r = f.showSaveDialog(null);
        if (r == f.APPROVE_OPTION) {
            File file = f.getSelectedFile();
            path = file.getAbsolutePath();

            new Thread(new Runnable() {
                @Override
                public void run() {
                    for (int i = 0; i <= 100; i++) {
                        //  jProgressBar1.setValue(i);
                        //jProgressBar1.setVisible(true);
                        jLabel16.setVisible(true);

                        try {
                            Thread.sleep(20);
                        } catch (NullPointerException e) {
                            JOptionPane.showMessageDialog(null, "Please select Valide Image", "Image Not Selected", 1);
                        } catch (InterruptedException ex) {
                            ex.printStackTrace();
                        }
                    }
                    jLabel10.setIcon(new ImageIcon(new ImageIcon(path).getImage().getScaledInstance(jLabel10.getWidth(), jLabel10.getHeight(), Image.SCALE_SMOOTH)));
                    //jProgressBar1.setVisible(false);
                    //jLabel10.setVisible(false);
                    jLabel16.setVisible(false);
                }
            }).start();

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String rp = path.replace('\\', '/');

        int itemid = 0;
        try {
            database.setData("insert into item values('0','" + jComboBox1.getSelectedItem() + "','" + jTextField1.getText() + "','" + jTextField2.getText() + "','" + Double.valueOf(jTextField4.getText()) + "','" + Double.valueOf(jTextField6.getText()) + "','" + jTextField5.getText() + "','" + jSpinner1.getValue() + "','" + jSpinner2.getValue() + "')");

            ResultSet rs = database.getData("select * from item order by item_id desc limit 1");
            while (rs.next()) {

                itemid = rs.getInt("item_id");

            }

            //System.out.println(itemid);
            database.setData("insert into camera values('" + jComboBox3.getSelectedItem() + "','" + rp + "','" + jComboBox2.getSelectedItem() + "','" + itemid + "')");

            JOptionPane.showMessageDialog(null, "Camera Successfully Added to System");
        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField8KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField8KeyReleased
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);
        int id = 0;
        try {

            ResultSet rs = database.getData("select * from item i, camera c where i.item_id = c.item_item_id and i.item_name like '" + jTextField8.getText() + "%" + "'");
            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getString("item_name"));
                v.add(rs.getString("model_number"));
                v.add(rs.getString("type"));
                v.add(rs.getString("c.lense_size"));
                v.add(rs.getString("c.mega_pixcel"));
                v.add(rs.getString("quantity"));
                v.add(rs.getString("cost_price"));
                v.add(rs.getString("barcode"));
                v.add(rs.getString("c.image"));
                v.add(rs.getString("selling_price"));
                v.add(rs.getString("warrenty"));

                dtm.addRow(v);

            }
        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_jTextField8KeyReleased
    String imgp;
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();

        // jTextField12.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());//BRAND
        jComboBox1.addItem(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
        jTextField1.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
        jTextField2.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString());
        jComboBox2.addItem(jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString());
        jComboBox3.addItem(jTable1.getValueAt(jTable1.getSelectedRow(), 4).toString());
        int spin2 = Integer.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 5).toString());
        jSpinner1.setValue(spin2);
        jTextField4.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 6).toString());
        jTextField5.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 7).toString());

        //  image loading for lable
        String n = jTable1.getValueAt(jTable1.getSelectedRow(), 8).toString();
        String x = n.replace('/', '\\');
        imgp = x;

        if (new File(n).exists()) {
            jLabel10.setIcon(new ImageIcon(new ImageIcon(x).getImage().getScaledInstance(jLabel10.getWidth(), jLabel10.getHeight(), Image.SCALE_SMOOTH)));
        } else {
            JOptionPane.showMessageDialog(null, "Image not Found Please Insert New Image Or Update Image");
        }

        jTextField6.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 9).toString());
        int spin1 = Integer.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 10).toString());
        jSpinner2.setValue(spin1);


    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        int itemid = 0;
        try {

            ResultSet rs = database.getData("select * from item  where barcode='" + jTextField5.getText() + "' ");
            while (rs.next()) {

                itemid = rs.getInt("item_id");
                System.out.println(itemid);

            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        //delete camera 
        try {
            database.setData("DELETE FROM camera WHERE item_item_id='" + itemid + "'");

        } catch (Exception e) {
            e.printStackTrace();
        }

        // delete items on  item table
        try {
            database.setData("DELETE FROM item WHERE item_id='" + itemid + "'");
            JOptionPane.showMessageDialog(null, "Camera Delete Successfully");
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        NewItem n = new NewItem();
        n.setVisible(true);


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       
        
        int item_id =0;
        
        try {
            ResultSet rs = database.getData("select * from item where barcode='"+jTextField5.getText()+"'");
            if (rs.next()) {                
                item_id=rs.getInt("item_id");
                System.out.println(item_id);
                
            }
            
        } catch (Exception e) {
        }
        
        
        try {
            database.setData("update item set quantity='"+jSpinner1.getValue()+"',cost_price='"+Double.valueOf(jTextField4.getText())+"',selling_price='"+Double.valueOf(jTextField6.getText())+"' where item_id = '"+item_id+"'");
            JOptionPane.showMessageDialog(null,"Item Update Successfully");
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        NewItem ni= new NewItem();
        ni.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       JFileChooser f = new JFileChooser();
        f.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter fil = new FileNameExtensionFilter("*.IMAGE", "jpeg");
        f.addChoosableFileFilter(fil);
        int r = f.showSaveDialog(null);
        if (r == f.APPROVE_OPTION) {
            File file = f.getSelectedFile();
            path = file.getAbsolutePath();

            new Thread(new Runnable() {
                @Override
                public void run() {
                    for (int i = 0; i <= 100; i++) {
                        //  jProgressBar1.setValue(i);
                        //jProgressBar1.setVisible(true);
                        jLabel27.setVisible(true);

                        try {
                            Thread.sleep(20);
                        } catch (NullPointerException e) {
                            JOptionPane.showMessageDialog(null, "Please select Valide Image", "Image Not Selected", 1);
                        } catch (InterruptedException ex) {
                            ex.printStackTrace();
                        }
                    }
                    jLabel26.setIcon(new ImageIcon(new ImageIcon(path).getImage().getScaledInstance(jLabel26.getWidth(), jLabel26.getHeight(), Image.SCALE_SMOOTH)));
                    //jProgressBar1.setVisible(false);
                    //jLabel10.setVisible(false);
                    jLabel27.setVisible(false);
                }
            }).start();

        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        String rp = path.replace('\\', '/');
        int itemid =0;
        try {
            
            database.setData("insert into item values ('0','"+jComboBox4.getSelectedItem()+"','"+jTextField3.getText()+"','"+jTextField7.getText()+"','"+Double.valueOf(jTextField9.getText())+"','"+Double.valueOf(jTextField11.getText())+"','"+jTextField10.getText()+"','"+jSpinner3.getValue()+"','"+jSpinner4.getValue()+"')");
            ResultSet rs = database.getData("select * from item order by item_id desc limit 1");
            
            while (rs.next()) {

                itemid = rs.getInt("item_id");

            }
            
            database.setData("insert into dvr values ('"+jComboBox5.getSelectedItem()+"','"+jTextField13.getText()+"','"+rp+"','"+itemid+"')");
            JOptionPane.showMessageDialog(null,"DVR Successfully Added");
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
          
        
        int item_id =0;
        
        try {
            ResultSet rs = database.getData("select * from item where barcode='"+jTextField10.getText()+"'");
            if (rs.next()) {                
                item_id=rs.getInt("item_id");
                System.out.println(item_id);
                
            }
            
        } catch (Exception e) {
        }
        
        
        try {
            database.setData("update item set quantity='"+jSpinner3.getValue()+"',cost_price='"+Double.valueOf(jTextField9.getText())+"',selling_price='"+Double.valueOf(jTextField11.getText())+"' where item_id = '"+item_id+"'");
            JOptionPane.showMessageDialog(null,"Item Update Successfully");
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        
        
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) jTable2.getModel();
        int itemid = 0;
        try {

            ResultSet rs = database.getData("select * from item  where barcode='" + jTextField10.getText() + "' ");
            while (rs.next()) {

                itemid = rs.getInt("item_id");
                System.out.println(itemid);

            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        //delete dvr 
        try {
            database.setData("DELETE FROM dvr WHERE item_item_id='" + itemid + "'");

        } catch (Exception e) {
            e.printStackTrace();
        }

        // delete items on  item table
        try {
            database.setData("DELETE FROM item WHERE item_id='" + itemid + "'");
            JOptionPane.showMessageDialog(null, "DVR Delete Successfully");
            dtm.removeRow(jTable2.getSelectedRow());
            
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButton11ActionPerformed

    private void jTextField12KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField12KeyReleased
          DefaultTableModel dtm = (DefaultTableModel) jTable2.getModel();
        dtm.setRowCount(0);
        int id = 0;
        try {

            ResultSet rs = database.getData("select * from item i, dvr d where i.item_id = d.item_item_id and i.item_name like '" + jTextField12.getText() + "%" + "'");
            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getString("item_name"));
                v.add(rs.getString("model_number"));
                v.add(rs.getString("type"));
                v.add(rs.getString("d.channels"));
                v.add(rs.getString("d.description"));
                v.add(rs.getString("quantity"));
                v.add(rs.getString("cost_price"));
                v.add(rs.getString("barcode"));
                v.add(rs.getString("d.image"));
                v.add(rs.getString("selling_price"));
                v.add(rs.getString("warrenty"));

                dtm.addRow(v);

            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        
        
        
        
    }//GEN-LAST:event_jTextField12KeyReleased

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
       DefaultTableModel dtm = (DefaultTableModel) jTable2.getModel();

        // jTextField12.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());//BRAND
        jComboBox4.addItem(jTable2.getValueAt(jTable2.getSelectedRow(), 0).toString());
        jTextField3.setText(jTable2.getValueAt(jTable2.getSelectedRow(), 1).toString());
        jTextField7.setText(jTable2.getValueAt(jTable2.getSelectedRow(), 2).toString());
        jComboBox5.addItem(jTable2.getValueAt(jTable2.getSelectedRow(), 3).toString());
        jTextField13.setText(jTable2.getValueAt(jTable2.getSelectedRow(), 4).toString());
        int spin2 = Integer.valueOf(jTable2.getValueAt(jTable2.getSelectedRow(), 5).toString());
        jSpinner3.setValue(spin2);
        jTextField9.setText(jTable2.getValueAt(jTable2.getSelectedRow(), 6).toString());
        jTextField10.setText(jTable2.getValueAt(jTable2.getSelectedRow(), 7).toString());

        //  image loading for lable
        String n = jTable2.getValueAt(jTable2.getSelectedRow(), 8).toString();
        String x = n.replace('/', '\\');
        imgp = x;

        if (new File(n).exists()) {
            jLabel26.setIcon(new ImageIcon(new ImageIcon(x).getImage().getScaledInstance(jLabel26.getWidth(), jLabel26.getHeight(), Image.SCALE_SMOOTH)));
        } else {
            JOptionPane.showMessageDialog(null, "Image not Found Please Insert New Image Or Update Image");
        }

        jTextField11.setText(jTable2.getValueAt(jTable2.getSelectedRow(), 9).toString());
        int spin1 = Integer.valueOf(jTable2.getValueAt(jTable2.getSelectedRow(), 10).toString());
        jSpinner4.setValue(spin1);
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jTextField20KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField20KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField20KeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JSpinner jSpinner4;
    private javax.swing.JSpinner jSpinner5;
    private javax.swing.JSpinner jSpinner6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables

    private void itemnameload() {

        try {
            ResultSet rs = database.getData("select * from new_item where item_type='Camera'");
            while (rs.next()) {

                jComboBox1.addItem(rs.getString("item_name"));

            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    private void cameralensesize() {
        jComboBox2.addItem("2.8mm");
        jComboBox2.addItem("3.6mm");
        jComboBox2.addItem("4.0mm");
        jComboBox2.addItem("6.0mm");
        jComboBox2.addItem("8.0mm");
        jComboBox2.addItem("12mm");
        jComboBox2.addItem("16mm");
        jComboBox2.addItem("25mm");
        jComboBox2.addItem("50mm");
        jComboBox2.addItem("75mm");

    }

    private void cammegapixecl() {
        jComboBox3.addItem("1MP");
        jComboBox3.addItem("2MP");
        jComboBox3.addItem("3MP");
        jComboBox3.addItem("4MP");
        jComboBox3.addItem("5MP");
        jComboBox3.addItem("6MP");
        jComboBox3.addItem("7MP");
        jComboBox3.addItem("8MP");
        jComboBox3.addItem("9MP");
        jComboBox3.addItem("10MP");
        jComboBox3.addItem("11MP");
        jComboBox3.addItem("12MP");
        jComboBox3.addItem("13MP");
        jComboBox3.addItem("14MP");
        jComboBox3.addItem("15MP");
        jComboBox3.addItem("16MP");
        jComboBox3.addItem("17MP");
        jComboBox3.addItem("18MP");
        jComboBox3.addItem("19MP");
        jComboBox3.addItem("20MP");

    }

    private void dvritemname() {
       
        
        try {
            
            ResultSet rs = database.getData("select * from new_item where item_type='DVR'");
            while (rs.next()) {                
                
                jComboBox4.addItem(rs.getString("item_name"));
                
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }

    private void dvrchannel() {
      
        jComboBox5.addItem("4 Channel");
        jComboBox5.addItem("8 Channel");
        jComboBox5.addItem("16 Channel");
        jComboBox5.addItem("32 Channel");
         jComboBox5.addItem("64 Channel");
     
        
        
    }
}
