/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kontrinex_solutions;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import static kontrinex_solutions.database.con;
import net.proteanit.sql.DbUtils;

/**
 
 * Subject - Social and Professional Project Management
 * Code Developed By Developer 1 -Ruzaik Mohomad
 * Student Number - 1821173
 * Group - 1
 */
public final class returns extends javax.swing.JPanel {
        
        Connection conn = null;
        PreparedStatement pst = null;
        ResultSet rs = null;
    /**
     * Creates new form dashboard
     */
    public returns() {
        initComponents();
        
        try {
            conn = database.getConnection();
            fillcombobox();
            fillcombobox1();
            fetch();
            fetch1();
            fetch2();
            fetch3();
            cbox_barcode1.setSelectedItem(null);
            cbox_invoiceid.setSelectedItem(null);
            
            
        } catch (Exception ex) {
            Logger.getLogger(returns.class.getName()).log(Level.SEVERE, null, ex);
        }
      
    }
   

        

     
    private void fetch(){
         try{
            String q = "select cus_id as 'Customer ID', cus_name as 'Customer Name', nic as 'National ID', dob as 'Date of Birth', phone_num as 'Phone Number', home_address as 'Home Address' from customer";
            pst=con.prepareStatement(q);
            rs = pst.executeQuery();
            
            tbl_customerdetails.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void fetch1(){
         try{
            String q1 = "select ret_it_id as 'Returned Item ID', returned_item as 'Returned Item', barcode as 'Barcode', returns_ret_id as 'Returns ID', customer_cus_id as 'Customer ID', invoice_id as 'Invoice ID', return_status as 'Return Status' from returned_item";
            pst=con.prepareStatement(q1);
            rs = pst.executeQuery();
            
            tbl_returneditem.setModel(DbUtils.resultSetToTableModel(rs));
            
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void fetch2(){
         try{
            String q2 = "select ret_id as 'Returns ID', return_date as 'Return Date', invoice_id as 'Invoice ID', cus_id as 'Customer ID' from returns";
            pst=con.prepareStatement(q2);
            rs = pst.executeQuery();
            
            tbl_returns.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
     private void fetch3(){
         try{
            String q1 = "select ret_it_id as 'Returned Item ID', returned_item as 'Returned Item', barcode as 'Barcode', returns_ret_id as 'Returns ID', customer_cus_id as 'Customer ID', invoice_id as 'Invoice ID', return_status as 'Return Status' from returned_item";
            pst=con.prepareStatement(q1);
            rs = pst.executeQuery();
            
            tbl_returneditem1.setModel(DbUtils.resultSetToTableModel(rs));
            
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void fillcombobox(){
        try{
            String sql = "SELECT * FROM item";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while(rs.next()){
                String barcode = rs.getString("barcode");
                cbox_barcode1.addItem(barcode);
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void fillcombobox1(){
        try{
            String sql = "SELECT * FROM sales_invoice";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while(rs.next()){
                String invoiceid = rs.getString("invoice_id");
                cbox_invoiceid.addItem(invoiceid);
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tab_returns = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        btn_addreturn = new javax.swing.JButton();
        lbl_barcode1 = new javax.swing.JLabel();
        txt_returndate = new com.toedter.calendar.JDateChooser();
        lbl_returndate = new javax.swing.JLabel();
        cbox_barcode1 = new javax.swing.JComboBox<>();
        lbl_returneditem = new javax.swing.JLabel();
        txt_returneditem = new javax.swing.JTextField();
        lbl_customerid = new javax.swing.JLabel();
        txt_cusid = new javax.swing.JTextField();
        box_makeasreturn = new javax.swing.JCheckBox();
        lbl_returneditem1 = new javax.swing.JLabel();
        txt_searchcus = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_customerdetails = new javax.swing.JTable();
        lbl_returnid = new javax.swing.JLabel();
        txt_returnid = new javax.swing.JTextField();
        cbox_invoiceid = new javax.swing.JComboBox<>();
        lbl_invoiceid = new javax.swing.JLabel();
        lbl_returnstatus = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_returneditem = new javax.swing.JTable();
        lbl_searchitem = new javax.swing.JLabel();
        txt_searchitem = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_returns = new javax.swing.JTable();
        lbl_searchret = new javax.swing.JLabel();
        txt_searchret = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        lbl_returnid1 = new javax.swing.JLabel();
        txt_returneditemid1 = new javax.swing.JTextField();
        lbl_barcode2 = new javax.swing.JLabel();
        txt_barcode2 = new javax.swing.JTextField();
        lbl_returneditem2 = new javax.swing.JLabel();
        txt_returneditem1 = new javax.swing.JTextField();
        lbl_returnsid2 = new javax.swing.JLabel();
        lbl_customerid1 = new javax.swing.JLabel();
        lbl_invoiceid1 = new javax.swing.JLabel();
        lbl_returnstatus1 = new javax.swing.JLabel();
        box_received = new javax.swing.JCheckBox();
        lbl_searchitem1 = new javax.swing.JLabel();
        txt_searchitem1 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbl_returneditem1 = new javax.swing.JTable();
        txt_returnsid1 = new javax.swing.JTextField();
        txt_cusid1 = new javax.swing.JTextField();
        txt_invoiceid1 = new javax.swing.JTextField();
        btn_confirmreturns = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 204, 204), null, null));
        setPreferredSize(new java.awt.Dimension(823, 543));

        tab_returns.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N

        jPanel1.setPreferredSize(new java.awt.Dimension(823, 543));

        btn_addreturn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_addreturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Add_item_positive-512.png"))); // NOI18N
        btn_addreturn.setText("  Add Returns");
        btn_addreturn.setFocusable(false);
        btn_addreturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addreturnActionPerformed(evt);
            }
        });

        lbl_barcode1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_barcode1.setText("Barcode");

        lbl_returndate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_returndate.setText("Return Date");

        cbox_barcode1.setName("Select"); // NOI18N
        cbox_barcode1.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cbox_barcode1PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        lbl_returneditem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_returneditem.setText("Returned Item");

        txt_returneditem.setEditable(false);
        txt_returneditem.setBackground(new java.awt.Color(255, 255, 255));

        lbl_customerid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_customerid.setText("Customer ID");

        txt_cusid.setEditable(false);
        txt_cusid.setBackground(new java.awt.Color(255, 255, 255));

        box_makeasreturn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        box_makeasreturn.setSelected(true);
        box_makeasreturn.setText("In Progress");

        lbl_returneditem1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_returneditem1.setText("Search");

        txt_searchcus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchcusKeyReleased(evt);
            }
        });

        tbl_customerdetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer ID", "Customer Name", "NIC", "Date of Birth", "Phone Number", "Home Address"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_customerdetails.setFocusable(false);
        tbl_customerdetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_customerdetailsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_customerdetails);
        if (tbl_customerdetails.getColumnModel().getColumnCount() > 0) {
            tbl_customerdetails.getColumnModel().getColumn(0).setResizable(false);
            tbl_customerdetails.getColumnModel().getColumn(0).setHeaderValue("Customer ID");
            tbl_customerdetails.getColumnModel().getColumn(1).setResizable(false);
            tbl_customerdetails.getColumnModel().getColumn(1).setHeaderValue("Customer Name");
            tbl_customerdetails.getColumnModel().getColumn(2).setResizable(false);
            tbl_customerdetails.getColumnModel().getColumn(2).setHeaderValue("NIC");
            tbl_customerdetails.getColumnModel().getColumn(3).setResizable(false);
            tbl_customerdetails.getColumnModel().getColumn(3).setHeaderValue("Date of Birth");
            tbl_customerdetails.getColumnModel().getColumn(4).setResizable(false);
            tbl_customerdetails.getColumnModel().getColumn(4).setHeaderValue("Phone Number");
            tbl_customerdetails.getColumnModel().getColumn(5).setResizable(false);
            tbl_customerdetails.getColumnModel().getColumn(5).setHeaderValue("Home Address");
        }

        lbl_returnid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_returnid.setText("Return ID");

        txt_returnid.setEditable(false);
        txt_returnid.setBackground(new java.awt.Color(255, 255, 255));

        lbl_invoiceid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_invoiceid.setText("Invoice ID");

        lbl_returnstatus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_returnstatus.setText("Return Status :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_barcode1)
                                    .addComponent(lbl_returneditem)
                                    .addComponent(lbl_returnid))
                                .addGap(42, 42, 42)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cbox_barcode1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txt_returnid, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txt_returneditem, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(109, 109, 109)
                                .addComponent(lbl_returnstatus)
                                .addGap(37, 37, 37)
                                .addComponent(box_makeasreturn))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_customerid)
                                    .addComponent(lbl_returndate)
                                    .addComponent(lbl_invoiceid))
                                .addGap(53, 53, 53)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_returndate, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbox_invoiceid, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_cusid, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btn_addreturn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(41, 41, 41))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_returneditem1)
                        .addGap(18, 18, 18)
                        .addComponent(txt_searchcus, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_returnid)
                    .addComponent(txt_returnid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbox_barcode1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_barcode1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_returnstatus)
                        .addComponent(box_makeasreturn))
                    .addComponent(lbl_returneditem)
                    .addComponent(txt_returneditem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_returndate)
                    .addComponent(txt_returndate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbox_invoiceid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_invoiceid, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_cusid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_customerid)))
                    .addComponent(btn_addreturn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_returneditem1)
                    .addComponent(txt_searchcus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tab_returns.addTab("Add Returns", jPanel1);

        jPanel2.setPreferredSize(new java.awt.Dimension(823, 543));

        tbl_returneditem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Returned Item ID", "Returned Item", "Barcode", "Returns ID", "Customer ID", "Invoice ID", "Return Status"
            }
        ));
        tbl_returneditem.setFocusable(false);
        jScrollPane2.setViewportView(tbl_returneditem);

        lbl_searchitem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_searchitem.setText("Search Returned Item");

        txt_searchitem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_searchitem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchitemKeyReleased(evt);
            }
        });

        tbl_returns.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Returns ID", "Return Date", "Invoice ID", "Customer ID"
            }
        ));
        tbl_returns.setFocusable(false);
        jScrollPane3.setViewportView(tbl_returns);

        lbl_searchret.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_searchret.setText("Search Returns");

        txt_searchret.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_searchret.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchretKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(233, 233, 233)
                                .addComponent(lbl_searchret)
                                .addGap(41, 41, 41)
                                .addComponent(txt_searchret, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addComponent(lbl_searchitem)
                .addGap(18, 18, 18)
                .addComponent(txt_searchitem, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_searchret)
                    .addComponent(txt_searchret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_searchitem)
                    .addComponent(txt_searchitem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tab_returns.addTab("Search Item Returns", jPanel2);

        jPanel4.setPreferredSize(new java.awt.Dimension(823, 543));

        lbl_returnid1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_returnid1.setText("Returned Item ID");

        txt_returneditemid1.setEditable(false);
        txt_returneditemid1.setBackground(new java.awt.Color(255, 255, 255));

        lbl_barcode2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_barcode2.setText("Barcode");

        txt_barcode2.setEditable(false);
        txt_barcode2.setBackground(new java.awt.Color(255, 255, 255));

        lbl_returneditem2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_returneditem2.setText("Returned Item");

        txt_returneditem1.setEditable(false);
        txt_returneditem1.setBackground(new java.awt.Color(255, 255, 255));

        lbl_returnsid2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_returnsid2.setText("Returns ID");

        lbl_customerid1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_customerid1.setText("Customer ID");

        lbl_invoiceid1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_invoiceid1.setText("Invoice ID");

        lbl_returnstatus1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_returnstatus1.setText("Return Status :");

        box_received.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        box_received.setSelected(true);
        box_received.setText("Received");

        lbl_searchitem1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_searchitem1.setText("Search");

        txt_searchitem1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchitem1KeyReleased(evt);
            }
        });

        tbl_returneditem1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Returned Item ID", "Returned Item", "Barcode", "Returns ID", "Customer ID", "Invoice ID"
            }
        ));
        tbl_returneditem1.setFocusable(false);
        tbl_returneditem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_returneditem1MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tbl_returneditem1);

        txt_returnsid1.setEditable(false);
        txt_returnsid1.setBackground(new java.awt.Color(255, 255, 255));

        txt_cusid1.setEditable(false);
        txt_cusid1.setBackground(new java.awt.Color(255, 255, 255));

        txt_invoiceid1.setEditable(false);
        txt_invoiceid1.setBackground(new java.awt.Color(255, 255, 255));

        btn_confirmreturns.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_confirmreturns.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Add_item_positive-512.png"))); // NOI18N
        btn_confirmreturns.setText("  Confirm Returns");
        btn_confirmreturns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_confirmreturnsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_searchitem1)
                        .addGap(18, 18, 18)
                        .addComponent(txt_searchitem1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_customerid1)
                                    .addComponent(lbl_invoiceid1))
                                .addGap(55, 55, 55)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_invoiceid1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_cusid1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_returnid1)
                                    .addComponent(lbl_barcode2)
                                    .addComponent(lbl_returneditem2)
                                    .addComponent(lbl_returnsid2))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_returneditemid1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_barcode2, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_returnsid1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_returneditem1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(119, 119, 119)
                                .addComponent(btn_confirmreturns, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(lbl_returnstatus1)
                                .addGap(37, 37, 37)
                                .addComponent(box_received)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_returnid1)
                    .addComponent(txt_returneditemid1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_barcode2)
                    .addComponent(txt_barcode2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_returneditem2)
                    .addComponent(txt_returneditem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_returnstatus1)
                    .addComponent(box_received))
                .addGap(8, 8, 8)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_returnsid2)
                    .addComponent(txt_returnsid1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_customerid1)
                            .addComponent(txt_cusid1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_invoiceid1)
                            .addComponent(txt_invoiceid1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btn_confirmreturns, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_searchitem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_searchitem1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tab_returns.addTab("Confirm Returns", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab_returns, javax.swing.GroupLayout.PREFERRED_SIZE, 823, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab_returns, javax.swing.GroupLayout.PREFERRED_SIZE, 543, Short.MAX_VALUE)
        );

        tab_returns.getAccessibleContext().setAccessibleName("Add Returns");
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addreturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addreturnActionPerformed
        // TODO add your handling code here:
        
        try{
         
           if(box_makeasreturn.isSelected()){
           String query = "INSERT into returns (return_date, cus_id, invoice_id) values (?, ?, ?)";
           pst = conn.prepareStatement(query);
           pst.setString(1, ((JTextField)txt_returndate.getDateEditor().getUiComponent()).getText());
           pst.setString(2, txt_cusid.getText());
           String invoiceid = cbox_invoiceid.getSelectedItem().toString();
           pst.setString(3, invoiceid);
           pst.execute();
           }
          else{
              JOptionPane.showMessageDialog(null, "Please tick the checkbox!");
           }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
        
         try{
           if(box_makeasreturn.isSelected()){
           String query1 = "SELECT ret_id from returns WHERE invoice_id=?";
           pst = conn.prepareStatement(query1);
           pst.setString(1, cbox_invoiceid.getSelectedItem().toString());
           rs = pst.executeQuery();
           while(rs.next()){
               String addretid = rs.getString("ret_id");
               txt_returnid.setText(addretid);
           }
           }
           else{
              //JOptionPane.showMessageDialog(null, "Please enter all fields!");
           }
           
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
         
         try{
           
           if(box_makeasreturn.isSelected()){
               String query2 = "INSERT into returned_item (returned_item, barcode, returns_ret_id, customer_cus_id, invoice_id, return_status) values (?, ?, ?, ?, ?, ?)";
               pst = conn.prepareStatement(query2);
               pst.setString(1, txt_returneditem.getText());
               pst.setString(2, cbox_barcode1.getSelectedItem().toString());
               pst.setString(3, txt_returnid.getText());
               pst.setString(4, txt_cusid.getText());
               pst.setString(5, cbox_invoiceid.getSelectedItem().toString());
               pst.setString(6, box_makeasreturn.getText());
               pst.execute();
               JOptionPane.showMessageDialog(null, "Record has been Successfully Inserted!");
               txt_returnid.setText(null);
               cbox_barcode1.setSelectedItem(null);
               txt_returneditem.setText(null);
               txt_returndate.setDate(null);
               cbox_invoiceid.setSelectedItem(null);
               txt_cusid.setText(null);
               txt_searchcus.setText(null);
               fetch();
           }
           else{
               JOptionPane.showMessageDialog(null, "Record Cannot be Inserted, Please Try Again!");
           }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
         
    }//GEN-LAST:event_btn_addreturnActionPerformed

    private void cbox_barcode1PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cbox_barcode1PopupMenuWillBecomeInvisible
        // TODO add your handling code here:
         try{
            String tmp = (String)cbox_barcode1.getSelectedItem();
            String query = "SELECT * FROM item where barcode=? ";
            pst = conn.prepareStatement(query);
            pst.setString(1,tmp);
            rs = pst.executeQuery();
            while(rs.next()){
                String returneditem = rs.getString("item_name");
                txt_returneditem.setText(returneditem);
            }
            if(cbox_barcode1.getSelectedItem() == "Select"){
                txt_returneditem.setText(null);
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_cbox_barcode1PopupMenuWillBecomeInvisible

    private void txt_searchcusKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchcusKeyReleased
        // TODO add your handling code here:
        String custsearch = txt_searchcus.getText();
        
        try{
            String query = "SELECT cus_id as 'Customer ID', cus_name as 'Customer Name', nic as 'National ID', dob as 'Date of Birth', phone_num as 'Phone Number', home_address as 'Home Address' FROM customer WHERE cus_id LIKE '%"+ custsearch + "%'";
            pst=conn.prepareStatement(query);
            rs=pst.executeQuery();
            tbl_customerdetails.setModel(DbUtils.resultSetToTableModel(rs));
            
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_txt_searchcusKeyReleased

    private void tbl_customerdetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_customerdetailsMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)tbl_customerdetails.getModel();
        
        int selectedRowIndex = tbl_customerdetails.getSelectedRow();
        
        txt_cusid.setText((model.getValueAt(selectedRowIndex, 0).toString()));
        
        
    }//GEN-LAST:event_tbl_customerdetailsMouseClicked

    private void txt_searchitemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchitemKeyReleased
        // TODO add your handling code here:
         String itemsearch = txt_searchitem.getText();
        
        try{
            String query = "select ret_it_id as 'Returned Item ID', returned_item as 'Returned Item', barcode as 'Barcode', returns_ret_id as 'Returns ID', customer_cus_id as 'Customer ID', invoice_id as 'Invoice ID', return_status as 'Return Status' from returned_item WHERE returns_ret_id LIKE '%"+ itemsearch + "%'";
            pst=conn.prepareStatement(query);
            rs=pst.executeQuery();
            tbl_returneditem.setModel(DbUtils.resultSetToTableModel(rs));
            
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_txt_searchitemKeyReleased

    private void txt_searchretKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchretKeyReleased
        // TODO add your handling code here:
        String retsearch = txt_searchret.getText();
        
        try{
            String query = "select ret_id as 'Returns ID', return_date as 'Return Date', invoice_id as 'Invoice ID', cus_id as 'Customer ID' from returns WHERE ret_id LIKE '%"+ retsearch + "%'";
            pst=conn.prepareStatement(query);
            rs=pst.executeQuery();
            tbl_returns.setModel(DbUtils.resultSetToTableModel(rs));
            
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_txt_searchretKeyReleased

    private void tbl_returneditem1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_returneditem1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)tbl_returneditem1.getModel();
        
        int selectedRowIndex = tbl_returneditem1.getSelectedRow();
        
        txt_returneditemid1.setText((model.getValueAt(selectedRowIndex, 0).toString()));
        txt_returneditem1.setText((model.getValueAt(selectedRowIndex, 1).toString()));
        txt_barcode2.setText((model.getValueAt(selectedRowIndex, 2).toString()));
        txt_returnsid1.setText((model.getValueAt(selectedRowIndex, 3).toString()));
        txt_cusid1.setText((model.getValueAt(selectedRowIndex, 4).toString()));
        txt_invoiceid1.setText((model.getValueAt(selectedRowIndex, 5).toString()));
    }//GEN-LAST:event_tbl_returneditem1MouseClicked

    private void txt_searchitem1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchitem1KeyReleased
        // TODO add your handling code here:
        String itemsearch = txt_searchitem1.getText();
        
        try{
            String query = "select ret_it_id as 'Returned Item ID', returned_item as 'Returned Item', barcode as 'Barcode', returns_ret_id as 'Returns ID', customer_cus_id as 'Customer ID', invoice_id as 'Invoice ID', return_status as 'Return Status' from returned_item WHERE returns_ret_id LIKE '%"+ itemsearch + "%'";
            pst=conn.prepareStatement(query);
            rs=pst.executeQuery();
            tbl_returneditem1.setModel(DbUtils.resultSetToTableModel(rs));
            
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_txt_searchitem1KeyReleased

    private void btn_confirmreturnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_confirmreturnsActionPerformed
        // TODO add your handling code here:
        try{
         if(box_received.isSelected()){
            String query = "UPDATE returned_item SET return_status=? WHERE ret_it_id=? ";
            pst = conn.prepareStatement(query);  
            pst.setString(1, box_received.getText());
            pst.setString(2, txt_returneditemid1.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Record has been Successfully Updated!");
            txt_returneditemid1.setText(null);
            txt_returneditem1.setText(null);
            txt_barcode2.setText(null);
            txt_returnsid1.setText(null);
            txt_cusid1.setText(null);
            txt_invoiceid1.setText(null);
            txt_searchitem1.setText(null);
            fetch3();
         }
         else{
             JOptionPane.showMessageDialog(null, "Record Cannot be Updated, Please Try Again!");
         }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btn_confirmreturnsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox box_makeasreturn;
    private javax.swing.JCheckBox box_received;
    private javax.swing.JButton btn_addreturn;
    private javax.swing.JButton btn_confirmreturns;
    private javax.swing.JComboBox<String> cbox_barcode1;
    private javax.swing.JComboBox<String> cbox_invoiceid;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lbl_barcode1;
    private javax.swing.JLabel lbl_barcode2;
    private javax.swing.JLabel lbl_customerid;
    private javax.swing.JLabel lbl_customerid1;
    private javax.swing.JLabel lbl_invoiceid;
    private javax.swing.JLabel lbl_invoiceid1;
    private javax.swing.JLabel lbl_returndate;
    private javax.swing.JLabel lbl_returneditem;
    private javax.swing.JLabel lbl_returneditem1;
    private javax.swing.JLabel lbl_returneditem2;
    private javax.swing.JLabel lbl_returnid;
    private javax.swing.JLabel lbl_returnid1;
    private javax.swing.JLabel lbl_returnsid2;
    private javax.swing.JLabel lbl_returnstatus;
    private javax.swing.JLabel lbl_returnstatus1;
    private javax.swing.JLabel lbl_searchitem;
    private javax.swing.JLabel lbl_searchitem1;
    private javax.swing.JLabel lbl_searchret;
    private javax.swing.JTabbedPane tab_returns;
    private javax.swing.JTable tbl_customerdetails;
    private javax.swing.JTable tbl_returneditem;
    private javax.swing.JTable tbl_returneditem1;
    private javax.swing.JTable tbl_returns;
    private javax.swing.JTextField txt_barcode2;
    private javax.swing.JTextField txt_cusid;
    private javax.swing.JTextField txt_cusid1;
    private javax.swing.JTextField txt_invoiceid1;
    private com.toedter.calendar.JDateChooser txt_returndate;
    private javax.swing.JTextField txt_returneditem;
    private javax.swing.JTextField txt_returneditem1;
    private javax.swing.JTextField txt_returneditemid1;
    private javax.swing.JTextField txt_returnid;
    private javax.swing.JTextField txt_returnsid1;
    private javax.swing.JTextField txt_searchcus;
    private javax.swing.JTextField txt_searchitem;
    private javax.swing.JTextField txt_searchitem1;
    private javax.swing.JTextField txt_searchret;
    // End of variables declaration//GEN-END:variables
}
