/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kontrinex_solutions;

import de.javasoft.plaf.synthetica.SyntheticaSimple2DLookAndFeel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 
 * Subject - Social and Professional Project Management
 * Code Developed By Developer 1 -Ruzaik Mohomad
 * Student Number - 1821173
 * Group - 1
 */
public class SplashScreen extends javax.swing.JFrame {

    /**
     * Creates new form SplashScreen
     */
    public SplashScreen() {
        initComponents();
        databse_check();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 204, 51));
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 460, 200, 30));

        jLabel15.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 102, 51));
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 570, 200, 30));

        jLabel16.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 102, 51));
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 490, 200, 30));

        jLabel17.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 255, 51));
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 530, 200, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/7647bb7539382dd708010625c4598021.gif"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 3, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(new SyntheticaSimple2DLookAndFeel());
        } catch (Exception e) {
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SplashScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
     private void databse_check() {

        new Thread(new Runnable() {
            @Override
            public void run() {

                for (int i = 0; i <= 100; i++) {
                    jLabel1.setVisible(true);
                        
                }
                try {
                    Class.forName("com.mysql.jdbc.Driver");
                    //Connection con=DriverManager.getconnection(url,"root","123"); 
                    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/information_schema", "root", "");
                    Statement st = con.createStatement();
                    ResultSet rs = st.executeQuery("select SCHEMA_NAME from SCHEMATA where SCHEMA_NAME='kontrinex_stockmanagement'");
                    if (rs.next()) {
                        
                try {

                    Thread.sleep(2000);

                    jLabel14.setText("Checking DataBase");
                    Thread.sleep(3000);

                    jLabel16.setText("Loading Backgrounds");
                    Thread.sleep(3000);

                    jLabel15.setText("Loading Software");

                    Thread.sleep(3000);
                    jLabel17.setText("Loading Success");
                    Thread.sleep(3000);
                    jLabel14.setText("Start");
                    Thread.sleep(1000);

                } catch (Exception e) {

                }
                dispose();
                new Login().setVisible(true);
                       

                    } else {
                        jLabel14.setText("Checking DataBase");
                        Thread.sleep(3000);
                        jLabel16.setText("Loading failed !");
                        Thread.sleep(1000);
                        dispose();
                        JOptionPane.showMessageDialog(null, "Your Database is Lost Please Restore and try Again", "Database warning", HEIGHT);
                        new restore_splash().setVisible(true);
                        
                        

                    }
                   

                } catch (Exception e) {

                }

               


            }

        }).start();

    }


}


