/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kontrinex_solutions;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 
 * Subject - Social and Professional Project Management
 * Code Developed By Developer 1 -Ruzaik Mohomad
 * Student Number - 1821173
 * Group - 1
 */
public final class vendor extends javax.swing.JPanel {

    Connection conn = null;
    PreparedStatement pst1 = null;
    ResultSet rs1 = null;

    /**
     * Creates new form dashboard
     */
    public vendor() {

        try {
            initComponents();

            conn = database.getConnection();
            txt_vendorid.setVisible(false);
            cbox_country.setSelectedItem(null);
            cbox_supplyingitems.setSelectedItem(null);
            
            fetchvendor();

        } catch (Exception ex) {
            Logger.getLogger(vendor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void fetchvendor() {

        try {
            String q1 = "select vendor_id as 'Vendor ID', company_name as 'Company Name', country as 'Country', web_site as 'Web Site', address as 'Address', supplying_item as 'Supplying Item' from vendor";
            pst1 = conn.prepareStatement(q1);
            rs1 = pst1.executeQuery();

            tbl_vendordetails.setModel(DbUtils.resultSetToTableModel(rs1));
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")


    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_companyname = new javax.swing.JLabel();
        lbl_country = new javax.swing.JLabel();
        lbl_website = new javax.swing.JLabel();
        lbl_address = new javax.swing.JLabel();
        lbl_supplyingitems = new javax.swing.JLabel();
        txt_companyname = new javax.swing.JTextField();
        cbox_country = new javax.swing.JComboBox<>();
        txt_website = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_address = new javax.swing.JTextPane();
        lbl_companyname1 = new javax.swing.JLabel();
        txt_search = new javax.swing.JTextField();
        btn_addvendor = new javax.swing.JButton();
        btn_modifyvendor = new javax.swing.JButton();
        btn_deletevendor = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_vendordetails = new javax.swing.JTable();
        cbox_supplyingitems = new javax.swing.JComboBox<>();
        txt_vendorid = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 204, 204), null, null));
        setPreferredSize(new java.awt.Dimension(823, 543));

        lbl_companyname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_companyname.setText("Company name");

        lbl_country.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_country.setText("Country");

        lbl_website.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_website.setText("Web Site");

        lbl_address.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_address.setText("Address");

        lbl_supplyingitems.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_supplyingitems.setText("Supplying Items");

        cbox_country.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Afghanistan", "Albania", "Algeria", "American Samoa", "Andorra", "Angola", "Anguilla", "Antigua and Barbuda", "Argentina", "Armenia", "Aruba", "Australia", "Austria", "Azerbaijan", "The Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bermuda", "Bhutan", "Bolivia", "Bosnia and Herzegovina", "Botswana", "Brazil", "Brunei", "Bulgaria", "Burkina Faso", "Burundi", "Cambodia", "Cameroon", "Canada", "Cape Verde", "Cayman Islands", "Central African Republic", "Chad", "Chile", "People 's Republic of China", "Republic of China", "Christmas Island", "Cocos(Keeling) Islands", "Colombia", "Comoros", "Congo", "Cook Islands", "Costa Rica", "Cote d'Ivoire", "Croatia", "Cuba", "Cyprus", "Czech Republic", "Denmark", "Djibouti", "Dominica", "Dominican Republic", "Ecuador", "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Ethiopia", "Falkland Islands", "Faroe Islands", "Fiji", "Finland", "France", "French Polynesia", "Gabon", "The Gambia", "Georgia", "Germany", "Ghana", "Gibraltar", "Greece", "Greenland", "Grenada", "Guadeloupe", "Guam", "Guatemala", "Guernsey", "Guinea", "Guinea - Bissau", "Guyana", "Haiti", "Honduras", "Hong Kong", "Hungary", "Iceland", "India", "Indonesia", "Iran", "Iraq", "Ireland", "Israel", "Italy", "Jamaica", "Japan", "Jersey", "Jordan", "Kazakhstan", "Kenya", "Kiribati", "North Korea", "South Korea", "Kosovo", "Kuwait", "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein", "Lithuania", "Luxembourg", "Macau", "Macedonia", "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands", "Martinique", "Mauritania", "Mauritius", "Mayotte", "Mexico", "Micronesia", "Moldova", "Monaco", "Mongolia", "Montenegro", "Montserrat", "Morocco", "Mozambique", "Myanmar", "Nagorno - Karabakh", "Namibia", "Nauru", "Nepal", "Netherlands", "Netherlands Antilles", "New Caledonia", "New Zealand", "Nicaragua", "Niger", "Nigeria", "Niue", "Norfolk Island", "Turkish Republic of Northern Cyprus", "Northern Mariana", "Norway", "Oman", "Pakistan", "Palau", "Palestine", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Pitcairn Islands", "Poland", "Portugal", "Puerto Rico", "Qatar", "Romania", "Russia", "Rwanda", "Saint Barthelemy", "Saint Helena", "Saint Kitts and Nevis", "Saint Lucia", "Saint Martin", "Saint Pierre and Miquelon", "Saint Vincent and the Grenadines", "Samoa", "San Marino", "Sao Tome and Principe", "Saudi Arabia", "Senegal", "Serbia", "Seychelles", "Sierra Leone", "Singapore", "Slovakia", "Slovenia", "Solomon Islands", "Somalia", "Somaliland", "South Africa", "South Ossetia", "Spain", "Sri Lanka", "Sudan", "Suriname", "Svalbard", "Swaziland", "Sweden", "Switzerland", "Syria", "Taiwan", "Tajikistan", "Tanzania", "Thailand", "Timor - Leste", "Togo", "Tokelau", "Tonga", "Transnistria Pridnestrovie", "Trinidad and Tobago", "Tristan da Cunha", "Tunisia", "Turkey", "Turkmenistan", "Turks and Caicos Islands", "Tuvalu", "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", "United States", "Uruguay", "Uzbekistan", "Vanuatu", "Vatican City", "Venezuela", "Vietnam", "British Virgin Islands", "Isle of Man", "US Virgin Islands", "Wallis and Futuna", "Western Sahara", "Yemen", "Zambia", "Zimbabwe" }));

        jScrollPane1.setViewportView(txt_address);

        lbl_companyname1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_companyname1.setText("Search");

        txt_search.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });

        btn_addvendor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Add_item_positive-512.png"))); // NOI18N
        btn_addvendor.setText("      Add Vendor");
        btn_addvendor.setMaximumSize(new java.awt.Dimension(153, 39));
        btn_addvendor.setMinimumSize(new java.awt.Dimension(153, 39));
        btn_addvendor.setPreferredSize(new java.awt.Dimension(153, 39));
        btn_addvendor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addvendorActionPerformed(evt);
            }
        });

        btn_modifyvendor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/ic_refresh_48px-512.png"))); // NOI18N
        btn_modifyvendor.setText("   Modify Vendor");
        btn_modifyvendor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modifyvendorActionPerformed(evt);
            }
        });

        btn_deletevendor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/close-128.png"))); // NOI18N
        btn_deletevendor.setText("  Delete Vendor");
        btn_deletevendor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deletevendorActionPerformed(evt);
            }
        });

        tbl_vendordetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Vendor ID", "Company Name", "Country", "Web Site", "Address", "Supplying Item"
            }
        ));
        tbl_vendordetails.setFocusable(false);
        tbl_vendordetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_vendordetailsMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_vendordetails);

        cbox_supplyingitems.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cameras", "DVR", "Accessories", "Camera Parts", "Security Devices and Others" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbl_supplyingitems)
                        .addGap(55, 55, 55)
                        .addComponent(cbox_supplyingitems, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_companyname)
                            .addComponent(lbl_country)
                            .addComponent(lbl_website)
                            .addComponent(lbl_address))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txt_website, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_companyname, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbox_country, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(lbl_companyname1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(txt_vendorid, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btn_deletevendor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_modifyvendor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_addvendor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(64, 64, 64))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_companyname1))
                        .addGap(15, 15, 15)
                        .addComponent(btn_addvendor, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_modifyvendor, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_deletevendor, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_companyname)
                            .addComponent(txt_companyname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_country)
                            .addComponent(cbox_country, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_website)
                            .addComponent(txt_website, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_vendorid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lbl_address)))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_supplyingitems)
                            .addComponent(cbox_supplyingitems, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_vendordetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_vendordetailsMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)tbl_vendordetails.getModel();
        int selectedRowIndex = tbl_vendordetails.getSelectedRow();
       try
    {
    // Your database connections 

    rs1= pst1.executeQuery("select vendor_id as 'Vendor ID', company_name as 'Company Name', country as 'Country', web_site as 'Web Site', address as 'Address', supplying_item as 'Supplying Item' from vendor");
    while(rs1.next()){
        txt_vendorid.setText((model.getValueAt(selectedRowIndex, 0).toString()));
        txt_companyname.setText((model.getValueAt(selectedRowIndex, 1).toString()));
        cbox_country.setSelectedItem((model.getValueAt(selectedRowIndex, 2).toString()));
        txt_website.setText((model.getValueAt(selectedRowIndex, 3).toString()));
        txt_address.setText((model.getValueAt(selectedRowIndex, 4).toString()));
        cbox_supplyingitems.setSelectedItem((model.getValueAt(selectedRowIndex, 5).toString()));
        btn_addvendor.setEnabled(false);
    }
   
    }
    catch(SQLException e)
    {
        System.out.println("Error"+e);
    }    
    }//GEN-LAST:event_tbl_vendordetailsMouseClicked

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
        // TODO add your handling code here:
        String vendsearch = txt_search.getText();
        
        try{
            String query = "select vendor_id as 'Vendor ID', company_name as 'Company Name', country as 'Country', web_site as 'Web Site', address as 'Address', supplying_item as 'Supplying Item' from vendor WHERE company_name LIKE '%"+ vendsearch + "%'";
            pst1=conn.prepareStatement(query);
            rs1=pst1.executeQuery();
            tbl_vendordetails.setModel(DbUtils.resultSetToTableModel(rs1));
            
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_txt_searchKeyReleased

    private void btn_addvendorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addvendorActionPerformed
        // TODO add your handling code here:
        try{
            if(txt_companyname.getText().isEmpty() || cbox_country.getSelectedItem().toString().isEmpty() || txt_website.getText().isEmpty() || txt_address.getText().isEmpty() || cbox_supplyingitems.getSelectedItem().toString().isEmpty()){
                JOptionPane.showMessageDialog(null, "Please enter all fields!");
            }
            else{
            String query = "INSERT into vendor (company_name, country, web_site, address, supplying_item) values (?, ?, ?, ?, ?)";
            pst1 = conn.prepareStatement(query);
            pst1.setString(1, txt_companyname.getText());
            String country = cbox_country.getSelectedItem().toString();
            pst1.setString(2, country);
            pst1.setString(3, txt_website.getText());
            pst1.setString(4, txt_address.getText());
            String supplyingitem = cbox_supplyingitems.getSelectedItem().toString();
            pst1.setString(5, supplyingitem);
            pst1.execute();
            JOptionPane.showMessageDialog(null, "Vendor Record has been Successfully Inserted!");
            fetchvendor();
            txt_companyname.setText(null);
            cbox_country.setSelectedItem(null);
            txt_website.setText(null);
            txt_address.setText(null);
            cbox_supplyingitems.setSelectedItem(null);
            }
            
            
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btn_addvendorActionPerformed

    private void btn_modifyvendorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modifyvendorActionPerformed
        // TODO add your handling code here:
        try{
            if(txt_companyname.getText().isEmpty() || cbox_country.getSelectedItem().toString().isEmpty() || txt_website.getText().isEmpty() || txt_address.getText().isEmpty() || cbox_supplyingitems.getSelectedItem().toString().isEmpty()){
                JOptionPane.showMessageDialog(null, "Please enter all fields!");
            }
            else{
            String query = "UPDATE vendor SET company_name=?, country=?, web_site=?, address=?, supplying_item=? WHERE vendor_id=? ";
            pst1 = conn.prepareStatement(query);
            pst1.setString(1, txt_companyname.getText());
            String country = cbox_country.getSelectedItem().toString();
            pst1.setString(2, country);
            pst1.setString(3, txt_website.getText());
            pst1.setString(4, txt_address.getText());
            String supplyingitem = cbox_supplyingitems.getSelectedItem().toString();
            pst1.setString(5, supplyingitem);
            pst1.setString(6, txt_vendorid.getText());
            pst1.executeUpdate();
            JOptionPane.showMessageDialog(null, "Vendor Record has been Successfully Updated!");
            fetchvendor();
            txt_companyname.setText(null);
            cbox_country.setSelectedItem(null);
            txt_website.setText(null);
            txt_address.setText(null);
            cbox_supplyingitems.setSelectedItem(null);
            btn_addvendor.setEnabled(true);
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btn_modifyvendorActionPerformed

    private void btn_deletevendorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deletevendorActionPerformed
        // TODO add your handling code here:
        try{
            if(txt_companyname.getText().isEmpty() || cbox_country.getSelectedItem().toString().isEmpty() || txt_website.getText().isEmpty() || txt_address.getText().isEmpty() || cbox_supplyingitems.getSelectedItem().toString().isEmpty()){
                JOptionPane.showMessageDialog(null, "Please enter all fields!");
            }
            else{
            String query = "DELETE FROM vendor WHERE vendor_id=? ";
            pst1 = conn.prepareStatement(query);
            pst1.setString(1, txt_vendorid.getText());
            pst1.execute();
            JOptionPane.showMessageDialog(null, "Vendor Record has been Successfully Deleted!");
            fetchvendor();
            txt_companyname.setText(null);
            cbox_country.setSelectedItem(null);
            txt_website.setText(null);
            txt_address.setText(null);
            cbox_supplyingitems.setSelectedItem(null);
            btn_addvendor.setEnabled(true);
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btn_deletevendorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addvendor;
    private javax.swing.JButton btn_deletevendor;
    private javax.swing.JButton btn_modifyvendor;
    private javax.swing.JComboBox<String> cbox_country;
    private javax.swing.JComboBox<String> cbox_supplyingitems;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbl_address;
    private javax.swing.JLabel lbl_companyname;
    private javax.swing.JLabel lbl_companyname1;
    private javax.swing.JLabel lbl_country;
    private javax.swing.JLabel lbl_supplyingitems;
    private javax.swing.JLabel lbl_website;
    private javax.swing.JTable tbl_vendordetails;
    private javax.swing.JTextPane txt_address;
    private javax.swing.JTextField txt_companyname;
    private javax.swing.JTextField txt_search;
    private javax.swing.JTextField txt_vendorid;
    private javax.swing.JTextField txt_website;
    // End of variables declaration//GEN-END:variables
}
